In [1]:
100+200

300

In [9]:
print("100+200 =",100+200)

100+200 = 300


In [11]:
name=input() gy

SyntaxError: invalid syntax (<ipython-input-11-26954f4df6dd>, line 1)

In [ ]:
name = input()
# print(name)

In [6]:
print(name)

aa


In [1]:
name = input()

aa


In [2]:
print(name)

aa


In [ ]:
name = input()

print('hallo,',name)

In [4]:
name = input('please enter ur name,')

print('hallo',name)

please enter ur name,aa
hallo aa


In [11]:
a = ['ABC', 'kevin']

b = a

# a.append('123'()
a = '123'

print(a)

123


In [13]:
b

['ABC', 'kevin']

In [18]:
classmate = ['waiting','egg','yueee']

In [20]:
len(classmate)

3

In [22]:
classmate[0]

'waiting'

In [31]:
print(classmate[0] + '\n' +classmate[1])

waiting
egg


In [33]:
classmate[3]

IndexError: list index out of range

In [35]:
classmate[-1]

'yueee'

In [37]:
classmate[-3]

'waiting'

In [39]:
classmate[-4]

IndexError: list index out of range

In [1]:
classmate.append('roy')

NameError: name 'classmate' is not defined

In [21]:
classmate = ['waiting','edd','ooo']


In [22]:
classmate

['waiting', 'edd', 'ooo']

In [23]:
classmate.append('rrr')
print(classmate)

['waiting', 'edd', 'ooo', 'rrr']


In [31]:
classmate.insert(1,'qwe')
print(classmate)

['waiting', 'qwe']


In [36]:
classmate[1] = 'qqq'
print(classmate)

['waiting', 'qqq']


In [42]:
t = (1)

In [44]:
t

1

In [53]:
t = ('a','b',['v','b'])
t[2][0] = 'l'
t[2][1] = 'g'

In [55]:
t

('a', 'b', ['l', 'g'])

In [69]:
L = [
    ['Apple', 'Google', 'Microsoft'],
    ['Java', 'Python', 'Ruby', 'PHP'],
    ['Adam', 'Bart', 'Lisa']
]

print(L[2][2])

Lisa


In [81]:
age = 5

if age >= 18:

   print('ur age is ', age)
   print('adult')
    
elif age >=10:

     print('teenager')
    
    
    
else:
    
    print('ur age is', age)
    print('kid')
    
   

ur age is 5
kid


In [ ]:
s = input('birth')
birth = int(s)

if birth < 2000:
    
      print('00 前')
        
else:
    
    print('00後')

In [ ]:
hight = float(a)

a = input('height')


b = input('weight')

weight = float(b)


# bmi = weight/(height*height)
bmi = weight/(height*height)

if bmi < 18.5:
    print('過輕')
    
elif 25 >= bmi >=18.5:
    print('正常')
    
elif  32 >= bmi >=28:
    print('肥胖')
    
else: 
    print('過肥')

In [1]:
names = ['e','r','t']

for name in names:

    print(name)

e
r
t


In [13]:
sum = 0

for x in [1,2,3,4,5,6,7,8,9,10]:
    
    sum = sum + x
    
print(sum)
    

55


In [17]:
list(range(5))


[0, 1, 2, 3, 4]

In [13]:
range(5)

range(0, 5)

In [14]:
sum = 0

for x in range (101):

    sum = sum + x

print(sum)

5050


In [18]:
sum = 0

n=9

while n > 0:

   sum = sum+n
    
   n = n-2
    
print(sum)

25


In [4]:
9+7+5+3+1

25

In [5]:
names = ['q','w','e']

for name in names:
    
    print('hallo',name)

hallo q
hallo w
hallo e


In [15]:
n = 1

while n <= 100:
    print(n)
    n=n+1
    
print('end')
    

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
end


In [7]:
n = 1

while n <=100:
   
    if n >20:

       break
    
    print(n)
    
    n = n+1
    
    
    
    
    

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [9]:
n = 0 

while n <10:
    n = n+2
    print(n)



2
4
6
8
10


In [6]:
n =0

while n <10:
    
    n= n+1

    if n%2==0:
    
      continue
    
    print(n)

1
3
5
7
9


In [9]:
d ={'q':100,'w':20,'e':60}
d['q']

100

In [17]:
name = ['q','w']
score=[50,90]

print(name,score)

['q', 'w'] [50, 90]


In [20]:
d['H'] = 60

d['H']

60

In [24]:
'H' in d

True

In [31]:
d.pop('w')

KeyError: 'w'

In [33]:
d

{'H': 60, 'q': 100}

In [35]:
d.pop('q')

KeyError: 'q'

In [37]:
d

{'H': 60}

In [63]:
s = set([1,2,3])

In [65]:
s

{1, 2, 3}

In [67]:
s.add(4)

In [69]:
s

{1, 2, 3, 4}

In [76]:
s1=set([1,2,3])
s2=set([2,3,4])

In [78]:
s1 | s2

{1, 2, 3, 4}

In [82]:
a='abc'

b=a.replace('a','A')

In [84]:
b

'Abc'

In [21]:
member_error = ['sam_liao@payez.com.tw','kevin_chen@payez.com.tw','i _love_sam','456']
member_without_error = list() #創一個ＬＩＳＴ叫 member_whithout_error
#member_without_error.append(member_error[1].split('@')[1])

for x in member_error:  
    if '@' in x: 
        member_without_error.append(x)
        
print(member_without_error)


['sam_liao@payez.com.tw', 'kevin_chen@payez.com.tw']


In [1]:
staffs = [['sam',623,'sam_liao@payez.com.tw'],
         ['charlotte',712,'charlotte_wang@payeasy.com.tw'],
         ['kevin',617,'kevin_huang@康迅.公司.台灣']]
staffs_domain = list()
for x in staffs:
    staffs_domain.append(x[2].split('@')[1])
print(staffs_domain)
#     for y in x:
#         if '@' in y:
#             x.append(y)b
#             print(x)    

['payez.com.tw', 'payeasy.com.tw', '康迅.公司.台灣']


In [94]:
staffs = [['sam',623,'sam_liao@payez.com.tw'],
         ['charlotte',123,'charlotte_wang@payeasy.com.tw'],
         ['kevin',617,'kevin_huang@康迅.公司.台灣']]
#staffs_domain = list()
for x in range(len(staffs)):
    str(x[1]):
        #staffs_domain.append(x)#.split('@')[1])
#print(staffs_domain)
print(staffs)

SyntaxError: invalid syntax (<ipython-input-94-3926a9f168b0>, line 6)

In [61]:
staffs = [['sam','623','sam_liao@payez.com.tw'],
          ['ccc','ccc@yahoo.com.tw','123']]
for i in range(len(staffs)):
    for x in staffs[i]:
        if len(x)>3:
            print(x)


sam_liao@payez.com.tw
ccc@yahoo.com.tw


In [58]:
range(x)

TypeError: 'str' object cannot be interpreted as an integer

In [78]:
print(staffs)

[['sam', 623, 'sam_liao@payez.com.tw'], ['charlotte', 712, 'charlotte_wang@payeasy.com.tw'], ['kevin', 617, 'kevin_huang@康迅.公司.台灣']]


In [30]:
wr = ['123',456,'345']
wr_new = [str(i) for i in wr]
print(wr_new)



['123', '456', '345']


In [31]:
wr_r = list
wr_r.append(wr[0],wr[3],wr[2])
#wr[0],wr[3],wr[2]
print(wr_r)


IndexError: list index out of range

In [2]:
range(20)
print(range(20))

range(0, 20)


In [9]:
n1 = 255
n2 = 1000
hex(n1
   )

'0xff'

In [17]:
def my_abs()
    if x >= 0:
        return x
    else:
        return -x
print(my_abs)

SyntaxError: invalid syntax (<ipython-input-17-f4c6a89a9d3e>, line 1)

In [21]:
import math
def quadratic(a,b,c):
#ax^2 + bx + c = 0
print(ax^2 + bx + c = 0)

IndentationError: expected an indented block (<ipython-input-21-6b123f9c846d>, line 4)

In [24]:
import math
math.sqrt(4)

2.0

In [43]:
import math
math.pi
print(pi)

3.141592653589793


In [48]:
def area (width,height):
    return width * height
w = 4
h = 5
print(w,h,area(w,h))

4 5 20


In [51]:
# import timeit

def THSR(StartStation, EndStation, SearchDate, SearchTime):
    
    import requests
    from bs4 import BeautifulSoup
    import pandas as pd
    
    station = {
     '南港':'2f940836-cedc-41ef-8e28-c2336ac8fe68',
     '台北':'977abb69-413a-4ccf-a109-0272c24fd490',
     '板橋':'e6e26e66-7dc1-458f-b2f3-71ce65fdc95f',
     '桃園':'fbd828d8-b1da-4b06-a3bd-680cdca4d2cd',
     '新竹':'a7a04c89-900b-4798-95a3-c01c455622f4',
     '苗栗':'e8fc2123-2aaf-46ff-ad79-51d4002a1ef3',
     '台中':'3301e395-46b8-47aa-aa37-139e15708779',
     '彰化':'38b8c40b-aef0-4d66-b257-da96ec51620e',
     '雲林':'5f4c7bb0-c676-4e39-8d3c-f12fc188ee5f',
     '嘉義':'60831846-f0e4-47f6-9b5b-46323ebdcef7',
     '台南':'9c5ac6ca-ec89-48f8-aab0-41b738cb1814',
     '左營':'f2519629-5973-4d08-913b-479cce78a356'
        }

    parameter = {
        'StartStation' : station.get(StartStation),
        'EndStation' : station.get(EndStation),
        'SearchDate' : SearchDate[:4] + '/' + SearchDate[4:6] + '/' + SearchDate[6:],
        'SearchTime' : SearchTime[:2] + ':' + SearchTime[2:],
        'SearchWay':'DepartureInMandarin'
        }
    
    url = 'https://www.thsrc.com.tw/tw/TimeTable/SearchResult'
    
#     start = timeit.default_timer() 計算高鐵網站回應時間
    html_result = BeautifulSoup(requests.post(url=url, data=parameter).text, 'lxml')
#     stop = timeit.default_timer()  計算高鐵網站回應時間
#     print(stop-start)              計算高鐵網站回應時間

    train_schedule = list() #宣告儲存時刻表變數
    for i in html_result.findAll('td', {'class':'toTouch'}): #找尋 html tag 裡面有 td 且屬性 class 為 toTouch
        for x in i.findAll('td'):
            if x.text != '':
                train_schedule.append(x.text)
                
    train_schedule_to_df = list()            
    train_index = len(train_schedule)
    start_iter = 0
    for x in range(3, train_index, 3):
        train_schedule_to_df.append(train_schedule[start_iter:x])
        start_iter = x
             
    df_columns = ['車次', '出發時間', '抵達時間']
    df_result = pd.DataFrame(data=train_schedule_to_df, columns=df_columns)
    
    return df_result
    
    
    

In [52]:
print(df_result)

NameError: name 'df_result' is not defined

In [62]:
import re
>>> pat='abc'
>>> string='123 abc abc abc'
>>> match = re.search(pat,string)
>>> match.group()


'abc'

In [1]:
match = re.findall(pat,string)
match

NameError: name 're' is not defined

In [1]:
import pandas as pd
url = 'http://www.stockq.org/market/asia.php'
pd.rad_html(url)[4]

AttributeError: module 'pandas' has no attribute 'rad_html'

In [19]:
import pandas as pd 
groups = ["a","b","c","d"]
ironmen = [20,3,4,55]
#shit = [5,7,9,0]
ironmen_dict = {"group":groups,"ironmen":ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
ironmen_df


group  ironmen
0     a       20
1     b        3
2     c        4
3     d       55

In [31]:
import pandas as pd 
groups = ["a","b","c","d"]
ironmen = [20,3,4,55]
shit = [5,7,9,0]
ironmen_dict = {"group":groups,"ironmen":ironmen,"shit":shit}
ironmen_df = pd.DataFrame(ironmen_dict)
ironmen_df_no_mw = ironmen_df.drop(0, axis = 0)
print(ironmen_df_no_mw)
print("------")
ironmen_df_no_groups = ironmen_df.drop("ironmen",axis = 1)
print(ironmen_df_no_groups)

  group  ironmen  shit
1     b        3     7
2     c        4     9
3     d       55     0
------
  group  shit
0     a     5
1     b     7
2     c     9
3     d     0


In [36]:
import pandas as pd 
groups = ["a","b","c","d"]
ironmen = [20,3,4,55]
shit = [5,7,9,0]
ironmen_dict = {"group":groups,"ironmen":ironmen,"shit":shit}
ironmen_df = pd.DataFrame(ironmen_dict)
print(ironmen_df.ix[:,"group"])
print("------------------------")
print(ironmen_df.ix[0])
print("---------------")
print(ironmen_df.ix[0,"group"])



0    a
1    b
2    c
3    d
Name: group, dtype: object
------------------------
group       a
ironmen    20
shit        5
Name: 0, dtype: object
---------------
a


/Users/heweiting/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:7: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  import sys


In [42]:
import pandas as pd 
groups = ["a","b","c","d"]
ironmen = [20,3,4,55]
shit = [5,7,9,0]
ironmen_dict = {"group":groups,"ironmen":ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
filter = ironmen_df["ironmen"]<10
ironmen_df[filter]



group  ironmen
1     b        3
2     c        4

In [46]:
import pandas as pd 
groups = ["a","b","c","d"]
ironmen = [20,3,4,55]
shit = [5,7,9,0]
ironmen_dict = {"groups":groups,"ironmen":ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
ironmen_df = pd.DataFrame(ironmen, columns = ["ironmen"], index = groups)
ironmen_df.sort_values(by = "ironmen")



ironmen
b        3
c        4
a       20
d       55

In [51]:
import pandas as pd 
groups = ["a","b","c","d"]
ironmen = [20,3,4,55]
shit = [5,7,9,0]
ironmen_dict = {"group":groups,"ironmen":ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
print(ironmen_df.sum())
print("----------------")
print(ironmen_df.mean())


group      abcd
ironmen      82
dtype: object
----------------
ironmen    20.5
dtype: float64


In [79]:
import pandas as pd

gender = ["male","male","female"]
name = ["billy","willy","mia"]

ironmen_df = pd.DataFrame(gender, columns = ["gender"], index = gender)
pd.value_counts(ironmen_df.gender)

male      2
female    1
Name: gender, dtype: int64

In [83]:
import numpy as np
import pandas as pd

groups = ["a","b",np.nan,"d"]
ironmen = [59,9,19,np.nan]
ironmen_dict = {"groups":groups, "ironmen":ironmen}

iromen_df = pd.DataFrame(ironmen_dict)

print(ironmen_df.ix[:,"groups"].isnull())


KeyError: 'groups'

In [85]:
ironmen = [46,8,11,11,4,56]
article_multiplier = [30,30,30,30,30,30]
articles = ironmen*article_multiplier
print(articles)

TypeError: can't multiply sequence by non-int of type 'list'

In [89]:
import numpy as np

ironmen = np.array([46,8,11,11,4,56])
print(type(ironmen))
x=ironmen*30
print(x)

<class 'numpy.ndarray'>
[1380  240  330  330  120 1680]


In [105]:
import requests


res = requests.post('http://www.thsrc.com.tw/tw/TimeTable/SearchResult',
                   data = payload)
print(res.text)


<!DOCTYPE html>
<html lang="zh-tw">


<link rel="canonical" href="https://www.thsrc.com.tw"/>

<meta charset="utf-8" />
<link rel="shortcut icon" href="/Content/favicon/favicon.ico" />
<link rel="apple-touch-icon" href="/Content/favicon/57_57.png" sizes="57x57" />
<link rel="apple-touch-icon" href="/Content/favicon/72_72.png" sizes="72x72" />
<link rel="apple-touch-icon" href="/Content/favicon/76_76.png" sizes="76x76" />
<link rel="apple-touch-icon" href="/Content/favicon/114_114.png" sizes="114x114" />
<link rel="apple-touch-icon" href="/Content/favicon/120_120.png" sizes="120x120" />
<link rel="apple-touch-icon" href="/Content/favicon/144_144.png" sizes="144x144" />
<link rel="apple-touch-icon" href="/Content/favicon/152_152.png" sizes="152x152" />
<link rel="apple-touch-icon-precomposed" href="/Content/favicon/57_57.png" sizes="57x57" />
<link rel="apple-touch-icon-precomposed" href="/Content/favicon/72_72.png" sizes="72x72" />
<link rel="apple-touch-icon-precomposed" href="/Conten

In [99]:
import numpy as np

my_2d_array = np.array([[1,True],[0,False]])

print(my_2d_array)

my_2d_array = np.array([[20,True],["zero",False]])

print(my_2d_array)

[[1 1]
 [0 0]]
[['20' 'True']
 ['zero' 'False']]


In [106]:
import requests
ptturl = 'https://www.ptt.cc/bbs/creditcard/index.html'
res = requests.get(ptturl)
print (res.text)

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		

<meta name="viewport" content="width=device-width, initial-scale=1">

<title>看板 creditcard 文章列表 - 批踢踢實業坊</title>

<link rel="stylesheet" type="text/css" href="//images.ptt.cc/bbs/v2.22/bbs-common.css">
<link rel="stylesheet" type="text/css" href="//images.ptt.cc/bbs/v2.22/bbs-base.css" media="screen">
<link rel="stylesheet" type="text/css" href="//images.ptt.cc/bbs/v2.22/bbs-custom.css">
<link rel="stylesheet" type="text/css" href="//images.ptt.cc/bbs/v2.22/pushstream.css" media="screen">
<link rel="stylesheet" type="text/css" href="//images.ptt.cc/bbs/v2.22/bbs-print.css" media="print">




	</head>
    <body>
		
<div id="topbar-container">
	<div id="topbar" class="bbs-content">
		<a id="logo" href="/">批踢踢實業坊</a>
		<span>&rsaquo;</span>
		<a class="board" href="/bbs/creditcard/index.html"><span class="board-label">看板 </span>creditcard</a>
		<a class="right small" href="/about.html">關於我們</a>
		<a class="right small" href="/con

In [108]:
from bs4 import BeautifulSoup
html_sample='\
<html>\
<body>\
<h1 id = "title">Hellow World</h1>\
<a href = "#"class= "link">This is link1</a>\
<a herf ="# link2" class= "link">This is link2</a>\
</body>\
</html>'
soup = BeautifulSoup(html_sample)
print(soup.text)

Hellow WorldThis is link1This is link2


/Users/heweiting/anaconda/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file /Users/heweiting/anaconda/lib/python3.6/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


In [465]:
soup = BeautifulSoup(html_sample)
header = soup.select('h1')
print(header)

[<h1 id="title">Hellow World</h1>]


/Users/heweiting/anaconda/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file /Users/heweiting/anaconda/lib/python3.6/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


In [112]:
soup = BeautifulSoup(html_sample)
alink=soup.select('a')
print(alink)
                 

[<a class="link" href="#">This is link1</a>, <a class="link" herf="# link2">This is link2</a>]


/Users/heweiting/anaconda/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file /Users/heweiting/anaconda/lib/python3.6/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


In [115]:
alink = soup.select('#title')
print(alink)

[<h1 id="title">Hellow World</h1>]


In [121]:
soup = BeautifulSoup(html_sample)
for link in soup.select('.link'):
    print(link)

<a class="link" href="#">This is link1</a>
<a class="link" herf="# link2">This is link2</a>


/Users/heweiting/anaconda/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file /Users/heweiting/anaconda/lib/python3.6/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


In [603]:
alinks = soup.select('a')
for link in alinks:
    print (link['href'])

javascript: history.back()
https://tw.news.yahoo.com/
http://www.nownews.com/


KeyError: 'href'

In [152]:
import requests
from bs4 import BeautifulSoup
section = requests.get('https://www.ptt.cc/bbs/creditcard/index.html')
soup = BeautifulSoup(section.text)
for ent in soup.select('.r-ent'):
    print(ent)

<div class="r-ent">
<div class="nrec"><span class="hl f2">2</span></div>
<div class="mark"></div>
<div class="title">
<a href="/bbs/creditcard/M.1508746074.A.3FC.html">[問題] 育嬰假辦卡詢問</a>
</div>
<div class="meta">
<div class="date">10/23</div>
<div class="author">camelot1123</div>
</div>
</div>
<div class="r-ent">
<div class="nrec"></div>
<div class="mark"></div>
<div class="title">
			
				&lt;nosecoolie&gt;板規1-12請至專板 警告一次 by moon
			
			</div>
<div class="meta">
<div class="date">10/23</div>
<div class="author">-</div>
</div>
</div>
<div class="r-ent">
<div class="nrec"><span class="hl f2">3</span></div>
<div class="mark"></div>
<div class="title">
<a href="/bbs/creditcard/M.1508751746.A.387.html">[問題] 國泰世華的機場停車優惠</a>
</div>
<div class="meta">
<div class="date">10/23</div>
<div class="author">orea2005</div>
</div>
</div>
<div class="r-ent">
<div class="nrec"><span class="hl f2">7</span></div>
<div class="mark"></div>
<div class="title">
<a href="/bbs/creditcard/M.1508754782.A.3F7.html">

/Users/heweiting/anaconda/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file /Users/heweiting/anaconda/lib/python3.6/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


In [59]:
for ent in soup.select('.r-ent'):
    title  = ent.select('.title')[0].text
    author = ent.select('.author')[0].text
    date   = ent.select('.date')[0].text
    nrec   = ent.select('.nrec')[0].text
    print(title,author,date,nrec)

In [178]:
for ent in soup.select('.r-ent'):
    alink = ent.select('a')[0]['href']
    print(alink)

/bbs/creditcard/M.1508746074.A.3FC.html


IndexError: list index out of range

In [183]:
domain = 'http://www.ptt.cc'
for ent in soup.select('.r-ent'):
    alink = domain+ent.select('a')[0]['href']
    print(alink)

http://www.ptt.cc/bbs/creditcard/M.1508746074.A.3FC.html


IndexError: list index out of range

In [455]:
detailurl = 'https://www.ptt.cc/bbs/creditcard/M.1508746074.A.3FC.html'
res = requests.get(detailurl)
soup = BeautifulSoup(res.text,'lxml')
print(soup.select('#main-content')[0].contents[4])

IndexError: list index out of range

In [447]:
from datetime import date,datetime

currenttime = datetime.now()
print (currenttime.strftime("%Y-%m-%d %H:%M:%S"))

a = '2014-05-03 14:00'
print(datetime.strptime(a, "%Y-%m-%d %H:%M"))

2017-10-30 17:00:19
2014-05-03 14:00:00


In [374]:
from datetime import date,datetime

time = soup.select('.article-meta-value')[3].text
print(datetime.strptime(time, '%a %b %d %H:%M:%S %Y'))

2017-10-23 16:07:52


In [375]:
import re

title = soup.select('.article-meta-value')[2].text
m = re.match('\[(.*)\].*',title)
if m: 
    atype = m.group(1)
print(atype)

問題


In [376]:
import re
m = re.match(r"(\w+)@(\w+)","david@largidate.com")
print(m.groups())

m = re.match(r"(\w+)@([a-z.]+)","david@largidate.com")
print(m.groups())

m = re.match(r"(\d+)\.(\d+)","1995.5")
print(m.groups())

('david', 'largidate')
('david', 'largidate.com')
('1995', '5')


In [420]:
import requests
from bs4 import BeautifulSoup
from datetime import date, datetime
import re

def pageDetail(detailurl):
    res  = requests.get(detailurl)
    soup = BeautifulSoup(res.text,'lxml')
    
    summary = soup.select('#main-content')[0].content[4]
    
    time = soup.select('.article-meta-value')[2].text
    dt = datetime.strptime(time, '%a %b %d %H:%M:%S %Y')
    
    return{'summary':summary,'dt':dt}


In [60]:
domain = 'http://www.ptt.cc'
pttary = []
for page in range(1999,1997,-1):
    ptturl = 'http://www.ptt.cc/bbs/creditcard/index{}.html'.format(page)
    section = requests.get(ptturl.format(page))
    soup = BeautifulSoup(section.text,'lxml')
    for ent in soup.select('.r-ent'):
        dic
        dic['title'] = ent.select('.title')[0].text
        dic['link']  = domain + ent.select('a')[0]['href']
        dic.update(pageDetail(dic['link']))
        pttary.append(dic)

NameError: name 'dic' is not defined

In [484]:
import requests
sporturl = 'https://tw.news.yahoo.com/baseball'
res = requests.get(sporturl)
print(res.text)

<!DOCTYPE html><html id="atomic" class="NoJs desktop" lang="zh-Hant-TW"><head prefix="og: http://ogp.me/ns#"><script>window.performance && window.performance.mark && window.performance.mark('PageStart');</script><meta charset="utf-8"/><meta name="msapplication-TileColor" content="#6e329d"/><meta name="msapplication-TileImage" content="https://s.yimg.com/os/mit/media/p/presentation/images/icons/win8-tile-1484740.png"/><meta name="referrer" content="origin"/><meta name="theme-color" content="#400090"/><meta name="twitter:dnt" content="on"/><meta name="twitter:site" content="@Yahoo"/><meta name="page" content="運動分類頁"/><meta name="twitter:description" content="Yahoo奇摩運動新聞讓你掌握世界體壇、NBA、MLB最新動態，聚焦多元、專業、平衡的分析報導。"/><meta name="twitter:image" content="http://l.yimg.com/os/mit/media/m/social/images/social_default_logo-1481777.png"/><meta name="twitter:image:src" content="http://l.yimg.com/os/mit/media/m/social/images/social_default_logo-1481777.png"/><meta name="twitter:title" content="運動 - Yahoo

In [4]:
import requests
from bs4 import BeautifulSoup
section = requests.get('https://tw.news.yahoo.com/baseball')
soup = BeautifulSoup(section.text,'lxml')
for ent in soup.select('.Mb(5px)'):
    print(ent)


<h3 class="Mb(5px)" data-reactid="12"><a class="C($c-fuji-grey-l) Fw(b) Fz(20px) Lh(23px) LineClamp(2,46px) Fz(17px)--sm1024 Lh(19px)--sm1024 LineClamp(2,38px)--sm1024 Td(n) C(#0078ff):h C(#000)" data-reactid="13" href="/mlb-%E6%9F%AF%E7%91%9E%E4%BA%9E%E5%A5%AA%E5%86%A0%E5%BE%8C%E7%90%83%E5%A9%9A-%E5%A5%B3%E5%8F%8B%E6%93%81%E5%90%BB%E7%AD%94%E6%87%89-055332155.html"><u class="StretchedBox" data-reactid="14"></u><!-- react-text: 15 -->MLB／柯瑞亞奪冠後求婚　女友擁吻答應<!-- /react-text --></a></h3>
<h3 class="Mb(5px)" data-reactid="40"><a class="C($c-fuji-grey-l) Fw(b) Fz(20px) Lh(23px) LineClamp(2,46px) Fz(17px)--sm1024 Lh(19px)--sm1024 LineClamp(2,38px)--sm1024 Td(n) C(#0078ff):h C(#000)" data-reactid="41" href="/%E5%A4%AA%E7%A9%BA%E4%BA%BA%E5%B0%81%E7%8E%8B-%E9%9A%8A%E5%8F%B2%E9%A6%96%E5%BA%A7%E4%B8%96%E7%95%8C%E5%A4%A7%E8%B3%BD%E5%86%A0%E8%BB%8D-080502790--mlb.html"><u class="StretchedBox" data-reactid="42"></u><!-- react-text: 43 -->太空人封王 隊史首座世界大賽冠軍<!-- /react-text --></a></h3>
<h3 class="Mb(5px)"

In [5]:
for ent in soup.select('.Mb(5px)'):
    alinks = ent.select('a')[0]['href']
    print(alinks)

/mlb-%E6%9F%AF%E7%91%9E%E4%BA%9E%E5%A5%AA%E5%86%A0%E5%BE%8C%E7%90%83%E5%A9%9A-%E5%A5%B3%E5%8F%8B%E6%93%81%E5%90%BB%E7%AD%94%E6%87%89-055332155.html
/%E5%A4%AA%E7%A9%BA%E4%BA%BA%E5%B0%81%E7%8E%8B-%E9%9A%8A%E5%8F%B2%E9%A6%96%E5%BA%A7%E4%B8%96%E7%95%8C%E5%A4%A7%E8%B3%BD%E5%86%A0%E8%BB%8D-080502790--mlb.html
/%E5%A4%AA%E7%A9%BA%E4%BA%BA%E5%A5%AA%E9%9A%8A%E5%8F%B2%E9%A6%96%E5%86%A0-%E5%9B%9E%E9%A1%A7%E7%B8%BD%E5%86%A0%E8%BB%8D%E8%B3%BD%E7%9A%843%E5%80%8B%E7%B2%BE%E5%BD%A9%E7%9E%AC%E9%96%93-074000797.html
/%E6%88%90%E5%B0%B1%E9%9A%8A%E5%8F%B2%E9%A6%96%E5%86%A0-altuve-%E4%BA%BA%E7%94%9F%E6%9C%80%E5%BF%AB%E6%A8%82%E6%99%82%E5%88%BB-072306556.html
/%E9%81%94%E6%AF%94%E4%BF%AE%E6%9C%89%E8%A2%AB%E6%89%93%E7%88%86-%E6%9B%B8%E5%83%AE-%E4%B8%89%E5%B1%80%E7%99%BB%E6%9D%BF%E7%82%BA%E6%99%82%E5%B7%B2%E6%99%9A-%E5%A4%AA%E7%A9%BA%E4%BA%BA%E5%8B%87%E5%A5%AA%E9%9A%8A%E5%8F%B255%E5%B9%B4%E9%A6%96%E5%86%A0-054620346--mlb.html
/%E7%8E%8B%E5%A4%A9%E9%91%AB5%E5%B1%80%E5%A5%BD%E6%8A%95-%E5%BF%A0%E5%AD%9D%E6%8C%B

In [6]:
domain = 'https://tw.news.yahoo.com/baseball'
for ent in soup.select('.Mb(5px)'):
    alinks = domain + ent.select('a')[0]['href']
    print(alinks)

https://tw.news.yahoo.com/baseball/mlb-%E6%9F%AF%E7%91%9E%E4%BA%9E%E5%A5%AA%E5%86%A0%E5%BE%8C%E7%90%83%E5%A9%9A-%E5%A5%B3%E5%8F%8B%E6%93%81%E5%90%BB%E7%AD%94%E6%87%89-055332155.html
https://tw.news.yahoo.com/baseball/%E5%A4%AA%E7%A9%BA%E4%BA%BA%E5%B0%81%E7%8E%8B-%E9%9A%8A%E5%8F%B2%E9%A6%96%E5%BA%A7%E4%B8%96%E7%95%8C%E5%A4%A7%E8%B3%BD%E5%86%A0%E8%BB%8D-080502790--mlb.html
https://tw.news.yahoo.com/baseball/%E5%A4%AA%E7%A9%BA%E4%BA%BA%E5%A5%AA%E9%9A%8A%E5%8F%B2%E9%A6%96%E5%86%A0-%E5%9B%9E%E9%A1%A7%E7%B8%BD%E5%86%A0%E8%BB%8D%E8%B3%BD%E7%9A%843%E5%80%8B%E7%B2%BE%E5%BD%A9%E7%9E%AC%E9%96%93-074000797.html
https://tw.news.yahoo.com/baseball/%E6%88%90%E5%B0%B1%E9%9A%8A%E5%8F%B2%E9%A6%96%E5%86%A0-altuve-%E4%BA%BA%E7%94%9F%E6%9C%80%E5%BF%AB%E6%A8%82%E6%99%82%E5%88%BB-072306556.html
https://tw.news.yahoo.com/baseball/%E9%81%94%E6%AF%94%E4%BF%AE%E6%9C%89%E8%A2%AB%E6%89%93%E7%88%86-%E6%9B%B8%E5%83%AE-%E4%B8%89%E5%B1%80%E7%99%BB%E6%9D%BF%E7%82%BA%E6%99%82%E5%B7%B2%E6%99%9A-%E5%A4%AA%E7%A9%BA%E4%BA%B

In [2]:
detailurl = 'https://tw.news.yahoo.com/%E4%B8%AD%E8%8F%AF%E8%81%B7%E6%A3%92-%E8%B3%BD%E6%A0%BC%E5%A8%818%E5%B1%80%E5%84%AA%E8%B3%AA%E5%85%88%E7%99%BC-%E6%84%9F%E8%AC%9D%E9%9A%8A%E5%8F%8B%E7%81%AB%E5%8A%9B%E6%94%AF%E6%8F%B4-163555808.html'
res = requests.get(detailurl)
soup = BeautifulSoup(res.text,'lxml')
for x in soup.select('span'):
    print(x)
#print(soup.select('span'))

NameError: name 'requests' is not defined

In [617]:
dic = {'a':100,'b':"yes",'c':0.98}
print(dic.get('a'))

100


In [624]:
for page in range(145309335,145309330,-1):
    sporturl ='https://tw.news.yahoo.com/baseball/index{}.html'.format(page)
    print(sporturl)

https://tw.news.yahoo.com/baseball/index145309335.html
https://tw.news.yahoo.com/baseball/index145309334.html
https://tw.news.yahoo.com/baseball/index145309333.html
https://tw.news.yahoo.com/baseball/index145309332.html
https://tw.news.yahoo.com/baseball/index145309331.html


In [626]:
 train_schedule_to_df = list()            
    train_index = len(train_schedule)
    start_iter = 0
    for x in range(3, train_index, 3):
        train_schedule_to_df.append(train_schedule[start_iter:x])
        start_iter = x
        print(x)

IndentationError: unexpected indent (<ipython-input-626-640aa430a4ff>, line 2)

In [49]:
def gy(n):
    if n ==1:
        return 1
    return n*gy(n-1)
print(gy(100))
    

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000


In [56]:
def ggyy(x):
    result = 1
    for i in range(2,x+1):
        result *= i
    return result

In [55]:
ggyy(100) 9332621544394
415268169923885626670049071596826438162146859296389521759999322991560894146397615651828625369792082722375825118
5210916864000000000000000000000000

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000

In [50]:
print(sum(range(101)))

5050


In [57]:
def gy(n):
    if n ==1:
        return 1
    return n*gy(n-1)
print(gy(100))
    

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000


In [69]:
participated_group = "Big Data"
current_ttl_articles = 4
is_particpating = True

my_status = {"group":participated_group,
             "ttl_articles":current_ttl_articles,
             "is_particpating":is_particpating}
print(my_status["group"],my_status["ttl_articles"])




Big Data 4


In [79]:
import numpy as np

ironmen = np.array([46,8,11,11,4,56])
print(ironmen)
print(type(ironmen))
x = ironmen*30
print(x)

[46  8 11 11  4 56]
<class 'numpy.ndarray'>
[1380  240  330  330  120 1680]


In [89]:
import numpy as np
my_np_array = np.array([1,2,3,4,5])
print(my_np_array**2)
my_2d_array = np.array([[1,3],[2,4]])
print(my_2d_array**2)

[ 1  4  9 16 25]
[[ 1  9]
 [ 4 16]]


In [94]:
import numpy as np

ironmen = np.array([46,8,11,11,4,56])
print(ironmen[3])
print(ironmen>10)
print(ironmen[ironmen>10])

11
[ True False  True  True False  True]
[46 11 11 56]


In [98]:
import numpy  as np
import pandas as pd

my_2d_array = np.array([[1,3],[2,4]])
my_df = pd.DataFrame(my_2d_array,columns = ["col1","col2"])
print(my_df)

   col1  col2
0     1     3
1     2     4


In [104]:
import pandas as pd

groups = ["modern web","dev0ps","cloud","big data","security","自我挑戰"]
ironmen = [46,8,12,12,6,58]          
ironmen_dict = {"groups":groups,"ironmen":ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
print(ironmen_df)


       groups  ironmen
0  modern web       46
1      dev0ps        8
2       cloud       12
3    big data       12
4    security        6
5        自我挑戰       58


In [117]:
import pandas as pd

groups = ["modern web","dev0ps","cloud","big data","security","自我挑戰"]
ironmen = [46,8,12,12,6,58]          
ironmen_dict = {"groups":groups,"ironmen":ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
print(ironmen_df.iloc[0:1,1])



0    46
Name: ironmen, dtype: int64


In [124]:
import pandas as pd

groups = ["modern web","dev0ps","cloud","big data","security","自我挑戰"]
ironmen = [46,8,12,12,6,58]          
ironmen_dict = {"groups":groups,"ironmen":ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
print(ironmen_df[ironmen_df.loc[:,"ironmen"]>10])


       groups  ironmen
0  modern web       46
2       cloud       12
3    big data       12
5        自我挑戰       58


In [128]:
import pandas as pd

groups_categorical = pd.Categorical(["modern web","dev0ps",
                                     "cloud","big data","security","自我挑戰"])
print(type(groups_categorical))

<class 'pandas.core.categorical.Categorical'>


In [131]:
ironmen = [49,8,12,12,6,61]
for ironman in ironmen:
    print(ironmen)

[49, 8, 12, 12, 6, 61]
[49, 8, 12, 12, 6, 61]
[49, 8, 12, 12, 6, 61]
[49, 8, 12, 12, 6, 61]
[49, 8, 12, 12, 6, 61]
[49, 8, 12, 12, 6, 61]


In [135]:
my_seq = list(range(11))
for x in my_seq:
    if x %2==0:
        print(x,"偶數")
    else:
        print(x,"奇數")

0 偶數
1 奇數
2 偶數
3 奇數
4 偶數
5 奇數
6 偶數
7 奇數
8 偶數
9 奇數
10 偶數


In [138]:
my_seq = list(range(1,11))
for x in my_seq:
    if x%3==0:
        print(x,"整除")
    elif x%3==1:
        print(x,"餘1")
    else:
        print(x,"餘2")
    
    

1 餘1
2 餘2
3 整除
4 餘1
5 餘2
6 整除
7 餘1
8 餘2
9 整除
10 餘1


In [141]:
ironmen = [49,8,12,12,6,61]
for ironman in ironmen:
    if(ironman<10):
        continue
    else:
        print(ironman)

49
12
12
61


In [143]:
import math 
def circle_calculate(radius,area = True):
    circle_area   = math.pi*radius**2
    circle_circum = 2*math.pi*radius
    if area ==True:
        return circle_area
    else:
        return circle_circum
    

In [146]:
circle_calculate(3,area = False)

18.84955592153876

In [149]:
ironmen = [50,8,16,12,6,62]
ironmen_artocles = list(map(lambda x : x *40,ironmen))
print(ironmen_artocles)

[2000, 320, 640, 480, 240, 2480]


In [151]:
def my_square(input_number):
    '計算平方'
    ans = input_number**2
    return ans

In [153]:
my_square(3)

9

In [172]:
def my_square(input_number):
    '計算平方數且有錯誤處理的函數'
    try:
        ans = input_number**2
        return ans
    except:
        print ("請輸入數值")

In [173]:
my_square('qw')

請輸入數值


In [175]:
def ironmen_list(**kwargs):
    '列出各組參賽鐵人數'
    for key in kwargs:
        print(key,":",kwargs[key],"人")
        

In [177]:
ironmen_list(a=21,b=34)

a : 21 人
b : 34 人


In [197]:
import pandas as pd

groups = ["mondern web","devops","cloud","big Data","security","自我挑戰組",""]
ironmen = [51,8,18,14,6,64,9]
ironmen_dict = {"group":groups,"ironmen":ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
ironmen_df.head(n=7)


group  ironmen
0  mondern web       51
1       devops        8
2        cloud       18
3     big Data       14
4     security        6
5        自我挑戰組       64
6                     9

In [206]:
class Ironmen:
    def _init_(self,group,partiicipants):
        self.group = group
        self.participants = participants
print(Ironmen)

<class '__main__.Ironmen'>


In [208]:
class Ironmen:
    def _init_(self,group,partiicipants):
        self.group = group
        self.participants = participants
modern_web = Ironmen("Modern Web",54)
print(modern_web)

TypeError: object() takes no parameters

In [219]:
import requests
from bs4 import BeautifulSoup
resp = requests.get("http://udn.com/news/index")
soup = BeautifulSoup(resp.text)
table = soup.select("#tab1")
print(table)

[<div id="tab1"> <dl> <dt><a class="taba " href="https://udn.com/news/story/6656/2815651"><b>14:30</b>李永得說客語被制止 綠委:價值錯亂到令人想爆炸</a></dt> <dt><a class="taba " href="https://stars.udn.com/star/story/10092/2815647"><b>14:30</b>台灣練習生赴南韓培訓1年 0生活費靠家人送錢</a></dt> <dt><a class="taba sp" href="https://udn.com/news/story/6656/2815646"><b>14:29</b>【重磅快評】去蔣化下的審議式民主... 限制了誰</a></dt> <dt><a class="taba " href="https://udn.com/news/story/11611/2815632"><b>14:28</b>川普與杜特蒂雙狂會晤 外界屏息以待</a></dt> <dt><a class="taba " href="https://udn.com/news/story/7250/2815638"><b>14:24</b>台股尾盤拉回修正 失守10700點大關</a></dt> <dt><a class="taba " href="https://udn.com/news/story/6656/2815645"><b>14:23</b>連續工作20個月是進步價值？柯P：我熱愛工作</a></dt> <dt><a class="taba " href="https://udn.com/news/story/7266/2815593"><b>14:19</b>嬰兒自己「爬出」子宮 剖腹自然產見證生命力</a></dt> <dt><a class="taba sp" href="https://udn.com/news/story/7266/2815636"><b>14:19</b>空污假來了 唯獨坐辦公室的人沒得放</a></dt> <dt><a class="taba " href="https://udn.com/news/story/7332/2815622"><b>14:15</b>陸

/Users/heweiting/anaconda/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file /Users/heweiting/anaconda/lib/python3.6/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


In [223]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(resp.text,"lxml")

table=soup.select("#tab1")

scope = table[0].select(".taba")
#print(scope.text)
print(scope[0].text)
print(scope[1].text)

14:30李永得說客語被制止 綠委:價值錯亂到令人想爆炸
14:30台灣練習生赴南韓培訓1年 0生活費靠家人送錢


In [235]:
for line in scope:
    print(line.text)


14:05川普訪中前 中美簽署適航協議
14:05台股開高走高 收漲54.15點
14:05違停男子持毒被捕 警驚：他三分之一人生在牢裡 
14:04基隆港建旅運大樓4億回饋金怎給？市議會惹議
14:0311月台指期漲54點
14:00港客開卡丁車病發無心跳 鈴鹿賽道樂園用AED救回一命
13:57陸年產近800萬畢業生 就業壓力大
13:54議員問喜歡張惠妹嗎？ 柯文哲：還好啦
13:52川普抵南韓 左右朝鮮半島局勢的「超級周」登場 


In [243]:
time = scope[0].select("b")
print(time[0].text)

14:05


In [249]:
news = scope[0].text
print(news[0:5])
print(news[5:])

14:05
川普訪中前 中美簽署適航協議


In [10]:
import requests
from bs4 import BeautifulSoup

def get_hotline_udnnews(url):
    resp = requests.get(url)
    
    if resp.status_code is 200:
        resp.encoding = 'utf-8'
        soup = BeautifulSoup(resp.text,'lxml')
        scope1 = soup.select("#tab1")
        scope2 = scope1[0].select(".taba")
        
        hot_lines = []
        
        for line in scope2:
            hot_lines.append(line.text)
        return hot_lines
    




if __name__=='__main__':
    udnnews_lines = get_hotline_udnnews("http://udn.com/news/index")
    i = 0
    
    while i < len(udnnews_lines):
        print(udnnews_lines[i])
        i += 1

12:46北捷擬跨足不動產 首要目標雙子星大樓
12:44中美關係 前香港特首董建華角色重要
12:43下令封殺質疑飛行員投共媒體 國民黨：馮世寬好大
12:42APEC 沈榮津陳美伶與陸官員握手寒暄
12:39這張照片透露警察悲哀 葉毓蘭：裝備果然得自購
12:38部落土地劃設若重疊 原民會：以口述歷史為依據
12:35蘋果得標新影集 安妮斯頓與薇絲朋主演
12:33美國加強對古巴制裁 古巴民眾叫苦連天
12:31傳承紅岩精神 陳敏爾瞻仰八路軍舊址


In [290]:
import requests
from bs4 import BeautifulSoup

def get_hotline_udnnews(url):
    resp = requests.get(url)
    
    if resp.status_code is 200:
        resp.encoding = 'utf-8'
        soup = BeautifulSoup(resp.text,'lxml')
        scope1 = soup.select("#tab1")
        scope2 = scope1[0].select(".taba")
        
        hot_lines = []
        
        for line in scope2:
            hot_lines.append(line.text)
        return hot_lines
    




if __name__=='__main__':
    udnnews_lines = get_hotline_udnnews("http://udn.com/news/index")
    i = 0
    udnnews = 0
    udnnews_dicts = {}
    while i < len(udnnews_lines):
        udnnews_dicts['time'] = udnnews_lines[i][:5]
        udnnews_dicts['title'] = udnnews_lines[i][5:]
        print("[{}]TITLE:{}".format(udnnews_dicts['time'],udnnews_dicts['title']))
        i += 1

[16:22]TITLE:NCAA／4人參加NBA選秀離隊 杜克男籃仍強悍
[16:15]TITLE:基期影響 10月出口成長幅度縮減為3％
[16:09]TITLE:松鼠害跳電 「電線路障」成玉里特殊街景
[16:07]TITLE:上網謊稱拍賣嬰兒尿布 高雄女子判刑1年2月得坐牢
[16:06]TITLE:反擊簡太郎 黃國昌：告我誣告不會比較無辜
[16:06]TITLE:買到高鐵「狐獴」車票 民眾：是能免費搭一年嗎？
[16:04]TITLE:15歲台灣美少女飆海豚音 驚豔四座
[16:03]TITLE:獨提案可連署統不行 黃智賢：國發會假平台真獨裁
[16:00]TITLE:簡太郎被控貪污 今反告黃國昌誣告


In [285]:
!pip install pyttsx


In [286]:
from gtts import gTTS
tts = gTTS(text='狂新聞',lang='zh')
tts.save('broadmission_madnews.mp3')
import webbrowser
webbrowser.open("broadmission_madnews.mp3")

True

In [291]:
import pyttsx

engine = pyttsx.init()
engine.say('ggfuck')
engine.runAndWait()

ModuleNotFoundError: No module named 'engine'

In [302]:
a = ['1','3','6','2']
print(a.sort)

<built-in method sort of list object at 0x111596248>


In [306]:
False and False

False

In [4]:
for a in range(10):
    print('number=',a,end=';')

number= 0;number= 1;number= 2;number= 3;number= 4;number= 5;number= 6;number= 7;number= 8;number= 9;

In [11]:
for n in range(20):
    if n %2 == 1:
        break
    print(n,end=' ')

0 

In [21]:
import requests
from bs4 import BeautifulSoup
res = requests.get('https://pages.tmall.com/wow/act/18132/industry-100719')
soup = BeautifulSoup(res.text, 'html.parser')
len(soup.select('.J_dynamic_data'))
    



19

In [35]:
import json
import pandas
jd = json.loads(soup.select('.J_dynamic_data')[1].text.strip())
df = pandas.DataFrame(jd['items'])
df.head()

af_1x1                                          brandLogo btnText couponUrl  \
0         //img.alicdn.com/bao/uploaded/i1/TB1YtZpmWigSK...                     
1         //img.alicdn.com/bao/uploaded/i1/TB1_r6mi6ihSK...                     
2         //img.alicdn.com/bao/uploaded/i1/TB1gMQjh2NNTK...                     
3         //img.alicdn.com/bao/uploaded/i1/TB16F2Fi2BNTK...                     
4         //img.alicdn.com/bao/uploaded/i1/TB1AnKomWagSK...                     

  couponValue  hideSalePoint  \
0                      False   
1                      False   
2                      False   
3                      False   
4                      False   

                                             iconImg itemActPrice  \
0  //img.alicdn.com/tps/TB1XVIxNXXXXXcyXXXXXXXXXX...         2??9   
1                                                            1??9   
2                                                             4?9   
3                                                            6??8   
4                                                            3??9   

  itemActPriceTitle       itemDesc  \
0            双11狂欢价  10日10点开卖 抢先加购   
1            双11狂欢价      加入购物车享多重礼   
2            双11狂欢价        再送百元大礼包   
3            双11狂欢价   双11尽享低价 抢先加购   
4            双11狂欢价      爆款新品 限量抢购   

                                             itemImg itemMPrice itemTagPrice  \
0  //img.alicdn.com/bao/uploaded/i1/TB1r46Gb4rI8K...       2??9         2999   
1  //img.alicdn.com/bao/uploaded/i1/TB15J4hbRTH8K...       1??9         1299   
2  //img.alicdn.com/bao/uploaded/i1/TB1Bqg2aXLM8K...        4?9          599   
3  //img.alicdn.com/bao/uploaded/i1/TB1SiYxaL6H8K...       6??8         6688   
4  //img.alicdn.com/bao/uploaded/i1/TB1j86uXj3z9K...       3??9         3899   

  itemTagPriceTitle          itemTitle  \
0                          OPPO R11s新品   
1                               荣耀畅玩7X   
2                                 红米4A   
3                    iPhone 8 Plus 64G   
4                       HUAWEI Mate 10   

                                             itemUrl salePoint  
0  //detail.tmall.com/item.htm?acm=lb-zebra-27325...            
1  //detail.tmall.com/item.htm?acm=lb-zebra-27325...            
2  //detail.tmall.com/item.htm?acm=lb-zebra-27325...            
3  //detail.tmall.com/item.htm?acm=lb-zebra-27325...            
4  //detail.tmall.com/item.htm?acm=lb-zebra-27325...

In [25]:
j_ary = []
for jdata in soup.select('.J_dynamic_data'):
    if jdata.text.strip() != '':
        jd = json.loads(jdata.text.strip())
        if isinstance(jd, dict) and jd.get('items'):            
            df = pandas.DataFrame(jd['items'])
        if isinstance(jd, list):
            df = pandas.DataFrame(jd)
        j_ary.append(df)

In [30]:
jdf = pandas.concat(j_ary)

In [98]:
#jdf.columns
jdf[['itemTitle', 'itemUrl', 'itemTagPrice']]

itemTitle                                            itemUrl  \
0                 NaN                                                NaN   
0         OPPO R11s新品  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
1              荣耀畅玩7X  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
2                红米4A  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
3   iPhone 8 Plus 64G  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
4      HUAWEI Mate 10  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
5        iPhone 8 64G  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
6                红米4X  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
7                 荣耀9  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
8         vivo X20全面屏  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
9             小米6 陶瓷版  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
10             荣耀8青春版  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
11           小米Note 3  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
12              美图T8s  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
13           魅蓝 Note6  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
14       iPhone 7 32G  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
15     HUAWEI P10 64G  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
0         OPPO R11s新品  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
1              荣耀畅玩7X  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
2                红米4A  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
3   iPhone 8 Plus 64G  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
4      HUAWEI Mate 10  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
5        iPhone 8 64G  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
6                红米4X  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
7                 荣耀9  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
8         vivo X20全面屏  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
9             小米6 陶瓷版  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
10             荣耀8青春版  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
11           小米Note 3  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
12              美图T8s  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
..                ...                                                ...   
0         无线充电器苹果安卓通用  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
1      iPhoneX/8无线充电器  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
2            双线圈无线充电器  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
3      苹果8/8plus/x无线充  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
4      绿联iPhoneX无线充电器  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
5       mophie苹果无线充电器  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
6       iPhoneX无线充电宝8  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
7      ANKER无线充电器适用苹果  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
8       罗马仕2W毫安大容量充电宝  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
9         羽博1万毫安便携充电宝  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
10     魔睿20000毫安数显充电宝  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
11     小米移动电源2C 20000  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
12       品胜双USB2万毫安充电  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
13    SOLOVE充电宝两万毫安纤薄  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
14       科势超薄充电宝便携自带线  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
15         爱国者OL10400  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
16         口红般大小迷你充电宝  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
17      ARUN/海陆通液晶充电宝  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
18    移动电源10000mAh快充版  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
19         绿联自带线苹果充电宝  //detail.tmall.com/item.htm?acm=lb-zebra-27325...   
20      苹果7/8/Plus钢化膜  //detail.tmall.com/item.htm?acm=lb-ze

In [99]:
def gy(n):
    if n ==1:
        return 1
    return n*gy(n-1)
print(gy(200))
    

788657867364790503552363213932185062295135977687173263294742533244359449963403342920304284011984623904177212138919638830257642790242637105061926624952829931113462857270763317237396988943922445621451664240254033291864131227428294853277524242407573903240321257405579568660226031904170324062351700858796178922222789623703897374720000000000000000000000000000000000000000000000000


In [341]:
i= 0
for x in range(1,101):
    i = x +i+i
    
print(i)

2535301200456458802993406410650


In [205]:
import requests
from bs4 import BeautifulStoneSoup  
res = requests.get('https://makeabooking.flyscoot.com/Book/Flight')
print(res)
#soup = BeautifulSoup(res.text,"lxml")
#soup1=soup.select('#rate-toggles')
#print(soup)

<Response [405]>


In [204]:
import requests
res = requests.get('http://rate.bot.com.tw/xrt?Lang=zh-TW')
print (res.text)

<!DOCTYPE html>
<html lang="zh-TW" class="no-js">
<head>
    <meta charset="utf-8" />
    <title>臺灣銀行牌告匯率</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="description" content="臺灣銀行匯率利率黃金牌價查詢">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
        <meta name="robots" content="index,follow" />

    <link rel="icon" tpye="image/x-icon" href="/favicon.ico">
    <link rel="stylesheet" href="/Content/css/font-awesome.min.css">



        <link rel="stylesheet" href="/Content/main.css?3.2.0">
    <style>
        h1 {
            margin: 0.7em 0 0.5em 0;
        }

            h1.hero__header {
                font-size: 30px;
                margin: 10px 0;
            }

            h1.hero__header_small {
                font-size: 26px;
                margin: 12px 0;
            }

            h1.hero__head

In [128]:
import pandas

dfs = pandas.read_html('http://rate.bot.com.tw/xrt?Lang=zh-TW')
dfs[0]


/Users/heweiting/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:5: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """


In [147]:
currency = currency.ix[:,0:5]
currency

/Users/heweiting/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


幣值 現金匯率-本行買入 現金匯率-本行賣出 即期匯率本行買入 即期匯率本行賣入
0       美金 (USD)  美金 (USD)     29.82    30.362    30.12    30.22
1       港幣 (HKD)  港幣 (HKD)     3.717     3.912    3.837    3.897
2       英鎊 (GBP)  英鎊 (GBP)     38.55     40.48    39.42    39.84
3       澳幣 (AUD)  澳幣 (AUD)     22.86     23.52    23.05    23.28
4   加拿大幣 (CAD)  加拿大幣 (CAD)     23.43     24.17     23.7    23.92
5   新加坡幣 (SGD)  新加坡幣 (SGD)     21.67     22.45    22.09    22.27
6   瑞士法郎 (CHF)  瑞士法郎 (CHF)     29.64      30.7    30.17    30.46
7       日圓 (JPY)  日圓 (JPY)    0.2573    0.2683   0.2637   0.2677
8     南非幣 (ZAR)  南非幣 (ZAR)         -         -     2.06     2.14
9     瑞典幣 (SEK)  瑞典幣 (SEK)      3.21      3.72     3.55     3.65
10      紐元 (NZD)  紐元 (NZD)     20.59     21.22    20.83    21.03
11      泰幣 (THB)  泰幣 (THB)    0.8075    0.9505    0.896    0.936
12  菲國比索 (PHP)  菲國比索 (PHP)      0.54     0.673        -        -
13    印尼幣 (IDR)  印尼幣 (IDR)   0.00188   0.00258        -        -
14      歐元 (EUR)  歐元 (EUR)      34.4     35.55     34.9     35.3
15      韓元 (KRW)  韓元 (KRW)   0.02525   0.02915        -        -
16    越南盾 (VND)  越南盾 (VND)   0.00096   0.00146        -        -
17    馬來幣 (MYR)  馬來幣 (MYR)     6.132     7.702        -        -
18    人民幣 (CNY)  人民幣 (CNY)     4.439     4.601    4.511    4.561

In [143]:
currency.columns=[u'幣值',u'現金匯率-本行買入',u'現金匯率-本行賣出',u'即期匯率本行買入','即期匯率本行賣入']


In [144]:
currency[u'幣別'] = currency[u'幣別'].str.extract('\((\w+)\)')


KeyError: '幣別'

In [312]:
currency

幣值 現金匯率-本行買入 現金匯率-本行賣出 即期匯率本行買入 即期匯率本行賣入
0       美金 (USD)  美金 (USD)     29.82    30.362    30.12    30.22
1       港幣 (HKD)  港幣 (HKD)     3.717     3.912    3.837    3.897
2       英鎊 (GBP)  英鎊 (GBP)     38.55     40.48    39.42    39.84
3       澳幣 (AUD)  澳幣 (AUD)     22.86     23.52    23.05    23.28
4   加拿大幣 (CAD)  加拿大幣 (CAD)     23.43     24.17     23.7    23.92
5   新加坡幣 (SGD)  新加坡幣 (SGD)     21.67     22.45    22.09    22.27
6   瑞士法郎 (CHF)  瑞士法郎 (CHF)     29.64      30.7    30.17    30.46
7       日圓 (JPY)  日圓 (JPY)    0.2573    0.2683   0.2637   0.2677
8     南非幣 (ZAR)  南非幣 (ZAR)         -         -     2.06     2.14
9     瑞典幣 (SEK)  瑞典幣 (SEK)      3.21      3.72     3.55     3.65
10      紐元 (NZD)  紐元 (NZD)     20.59     21.22    20.83    21.03
11      泰幣 (THB)  泰幣 (THB)    0.8075    0.9505    0.896    0.936
12  菲國比索 (PHP)  菲國比索 (PHP)      0.54     0.673        -        -
13    印尼幣 (IDR)  印尼幣 (IDR)   0.00188   0.00258        -        -
14      歐元 (EUR)  歐元 (EUR)      34.4     35.55     34.9     35.3
15      韓元 (KRW)  韓元 (KRW)   0.02525   0.02915        -        -
16    越南盾 (VND)  越南盾 (VND)   0.00096   0.00146        -        -
17    馬來幣 (MYR)  馬來幣 (MYR)     6.132     7.702        -        -
18    人民幣 (CNY)  人民幣 (CNY)     4.439     4.601    4.511    4.561

In [311]:
import requests 
from bs4 import BeautifulSoup
res = requests.get("https://www.xinshipu.com/zuofa/686409")
#print(res.encoding = 'utf-8')
soup = BeautifulSoup(res.text,"lxml")
reup = soup.select('.content')[0]
print(reup.select('.subtitle.cg1')[0].text)
#print(reup.select('.ptm12.mlr1.btm')[0].text)
#print(reup.select('.subtitle.cg1')[1].text)
#print(reup.select('.pm12')[0].text)

材料


In [308]:
import requests 
from bs4 import BeautifulSoup
res = requests.get("https://www.xinshipu.com/zuofa/686409")
#print(res.encoding = 'utf-8')
soup = BeautifulSoup(res.text,"lxml")
reup = soup.select('.content')[0]
print(reup.select('.font16.ml10.col'))

[]


In [323]:
import requests 
headers = {'User-agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36'}
res = requests.get('https://www.stockdog.com.tw/stockdog/index.php?m=overview&sid=1101%20%E5%8F%B0%E6%B3%A5',headers=headers)
print(res.text)

<!DOCTYPE html><html xmlns="https://www.w3.org/1999/xhtml" xml:lang="zh">
<head>
	
<meta name="msvalidate.01" content="3764D27CDB130C3A8E503E7FF8B5B28F" />
<meta name="google-site-verification" content="0fOUYR1Hn_d2EBP9qlLwukSoK1VtspmJP6LMb_G73LQ" />
<meta name="alexaVerifyID" content="GQTKRctE0WejXC6jTID7sDp6agc" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta property="og:type" content="product"/>
<meta property="og:url" content="https://www.stockdog.com.tw/stockdog/"/>
<meta property="og:locale" content="zh-TW"/>
<meta property="og:image" content="https://www.stockdog.com.tw/stockdog/images/logo.png"/>
<meta property="og:site_name" content="股狗網-股市籌碼分析"/>
<meta property="og:description" content="每日最新的台股資料。 提供券商每日進出資料，分析主力進出。個股買賣日報讓你掌握賣賣個股時機！"/>
<meta property="fb:app_id" content="268329956608070" />
<meta name="keywords" content="股狗,股狗網,,,StockDog,籌碼分析,股市籌碼分析,籌碼面,主力,買賣日報,券商進出,券商分點,權證,權證日報,創新高,十年高,五年高,三年高,一年高,創新低,吃貨,出貨" /> 
<meta name="description" conte

In [1]:
def fib(i):
    if i <= 1:   # 當 i <= 1 時,
        return i  #  就結束 fib() 函式的遞迴呼叫.
    else: # 繼續遞迴呼叫 fib() 函式.
        return fib(i - 1) + fib(i - 2)

for i in range(10): # 利用迴圈印出 1~10 的費式數列.
       print( "fibonacci(" + str(i) + ")=" + str(fib(i)))



fibonacci(0)=0
fibonacci(1)=1
fibonacci(2)=1
fibonacci(3)=2
fibonacci(4)=3
fibonacci(5)=5
fibonacci(6)=8
fibonacci(7)=13
fibonacci(8)=21
fibonacci(9)=34


In [26]:
l = []
n=1
while n <=99:
    l.append(n)
    
    
    n = n+2
l

[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99]

In [12]:
print(l)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


In [17]:
L = ['michael','sarah','tracy','bob','jack']

In [25]:
r = []
n = 3
for i in range(n):
    r.append(L[i])
    

print(r)

['michael', 'sarah', 'tracy']


In [33]:
L[-2:]

['bob', 'jack']

In [36]:
L = list(range(100))
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [45]:
L[:5]

[0, 1, 2, 3, 4]

In [48]:
(0,1,2,3,4,5)[:3]

(0, 1, 2)

In [50]:
for i , value in enumerate(['a','b','c']):
    print(i,value)

0 a
1 b
2 c


In [89]:
d = {'a':1,'b':2,'c':3}
for key  in d:
    print(key)

a
b
c


In [54]:
for ch in 'abc':
    print(ch)

a
b
c


In [58]:
for a , value in enumerate(['a','b','c']):
    print(a,value)

0 a
1 b
2 c


In [61]:
for a , v in enumerate(['a','b','c']):
    print(a,v)

0 a
1 b
2 c


In [66]:
for x,y in[(1,1),(2,4),(3,9)]:
    print(x,y)

1 1
2 4
3 9


In [70]:
L = []
for x in range(1,11):
    L.append(x*x)
L

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [77]:
[x*x for x in range(1,11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [78]:
[x*x for x in range(1,11) if x % 2==0]

[4, 16, 36, 64, 100]

In [80]:
[m+n for m in 'abc' for n in 'xyz']

['ax', 'ay', 'az', 'bx', 'by', 'bz', 'cx', 'cy', 'cz']

In [90]:
import os
for a in os.listdir('.'):
    print(a)


.DS_Store
.ipynb_checkpoints
.localized
105年10月7日漁業署及海洋局拜會慶富討論如何取得興達港土地.mp3
1111.xlsx
broadmission_madnews.mp3
IMG_6716.jpg
IMG_6717.jpg
IMG_6718.jpg
IMG_6719.jpg
python test.ipynb
SW_DVD5_Office_Mac_Standard_2016_MultiLang_-3_.iso_MLF_X20-52737.ISO
爬高鐵資料.ipynb
螢幕快照 2017-09-19 下午11.24.23.png
螢幕快照 2017-09-20 下午2.16.46.png
螢幕快照 2017-09-20 下午2.16.55.png
螢幕快照 2017-09-20 下午2.17.08.png
螢幕快照 2017-09-20 下午2.57.07.png
螢幕快照 2017-09-20 下午5.20.01.png
螢幕快照 2017-09-20 下午5.24.07.png
螢幕快照 2017-09-20 下午5.26.39.png
螢幕快照 2017-09-20 下午6.46.59.png
螢幕快照 2017-09-20 下午6.51.13.png
螢幕快照 2017-09-20 下午7.17.50.png
螢幕快照 2017-09-25 上午11.40.56.png
螢幕快照 2017-11-13 下午8.46.13.png
螢幕快照 2017-11-13 下午8.57.04.png
螢幕快照 2017-11-13 下午8.57.20.png
螢幕快照 2017-11-13 下午8.58.26.png


In [94]:
d= {'x':'a','y':'b','z':'c'}
for k,v in d.items():
    print(k,'=',v)

x = a
y = b
z = c


In [96]:
d= {'x':'a','y':'b','z':'c'}
[k + '='+v for k,v in d.items()]

['x=a', 'y=b', 'z=c']

In [111]:
L = ['HE','WEE','RUU']
[s.lower() for s  in L]

['he', 'wee', 'ruu']

In [113]:
def fib(max):
    n,a,b = 0,0,1
    while n <max:
        print(b)
        a,b = b,a+b
        n=n+1
    return 'done'

In [115]:
fib(10)

1
1
2
3
5
8
13
21
34
55


'done'

In [121]:
name = 'fuck'
number = '12'

In [172]:
print('hey,my name is {} and my number is {}'.format(name,number))

hey,my name is fuck and my number is 12


In [179]:
f = 'wogo!@hhh'

In [182]:
f.split('o')[0]

'w'

In [183]:
price = 300

In [185]:
price**0.5

17.320508075688775

In [187]:
import math
math.sqrt(300)

17.320508075688775

In [188]:
stock_index = 'sp500'
price = 300

In [194]:
print('the {} is at {}'.format(stock_index,price))

the sp500 is at 300


In [195]:
stock_info = {'sp500':{'today':300,'yesterday':250},
              'info':['time',[24,7,365]]}

In [204]:
stock_info['sp500']['yesterday']

250

In [208]:
stock_info['info'][1][2]

365

In [214]:
def source_finder(s):
    return s.split('--')[1]

In [216]:
source_finder('price:345.324:source--quandl')

'quandl'

In [232]:
def price_finder(s):
    return 'PRICE' in s.upper()

In [234]:
price_finder('what price')

True

In [237]:
s = 'Wow that is a nice price, very nice PriceI  i am PRice'

In [283]:
def count_price(s):
    count = 0
    for word in s.lower().split():
        if 'price' in word:
            count = count+1
            
    return count

In [272]:
s = 'Wow that is a nice price in, very nice Price ,i am PRice'

In [285]:
count_price(s)

3

In [294]:
def count_price(s):
    return s.lower().count('price')

In [295]:
count_price(s)

3

In [298]:
def avg_price(stocks):
    return sum(stocks)/len(stocks)

In [301]:
avg_price([3,4,6])

4.333333333333333

In [305]:
import numpy as np
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [311]:
np.zeros((5,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [326]:
np.linspace(1,100,10)

array([   1.,   12.,   23.,   34.,   45.,   56.,   67.,   78.,   89.,  100.])

In [329]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [350]:
np.random.rand(3,6)

array([[ 0.27333415,  0.17832126,  0.99984139,  0.58386675,  0.28767379,
         0.26238484],
       [ 0.4177959 ,  0.77404128,  0.67914537,  0.34745611,  0.43001897,
         0.11651917],
       [ 0.63765831,  0.51573262,  0.32220656,  0.66015115,  0.9276757 ,
         0.18546769]])

In [369]:
np.random.randint(1,100,10)

array([73, 40, 63, 92, 45, 44, 44, 95, 30, 94])

In [373]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [381]:
arr = np.arange(0,10)

In [377]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [383]:
arr = np.arange(0,100)

In [385]:
import numpy as np

In [389]:
arr = np.arange(0,11)

In [395]:
arr[0:5] = 100

In [2]:
arr

NameError: name 'arr' is not defined

In [3]:
import scrapy

class HelloSpider(scrapy.Spider):
    name = "hello"

    def start_requests(self):
        urls = [
            'http://24h.pchome.com.tw/index/',
        ]
        for url in urls:
            yield scrapy.Request(url=url, callback=self.parse)

    def parse(self, response):
        page = response.url.split("/")[-2]
        filename = 'pchome-%s.html' % page
        with open(filename, 'wb', encoding='utf-8') as f:
            f.write(response.body)
        self.log('Saved file %s' % filename)

In [1]:
import scrapy

class LtnsearchItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    #pass
    title = scrapy.Field()
    link = scrapy.Field()
    body = scrapy.Field()
    postdate = scrapy.Field()

In [3]:
import urllib.request

if __name__ == '__main__':
    uri = "https://www.mobile01.com/forumtopic.php?c=16&p=1"
    handle = urllib.request.urlopen(uri)
    encoding = handle.headers.get_content_charset()
    html_data =  handle.read().decode(encoding)
    for a in html_data.split('class="topic_top" title="')[1:]:
        title = a.split('">')[1].split('</a>')[0]
        link = 'https://www.mobile01.com/'+a.split('href="')[1].split('">')[0]
        print(title)
        print(link)


亞太魔速方塊超展開，訊號、通話更順暢！北中南體驗會開跑
https://www.mobile01.com/topicdetail.php?f=18&t=5302442&p=5
【發表會直擊】美圖V6前後雙鏡頭加持 景深美照輕鬆get
https://www.mobile01.com/topicdetail.php?f=586&t=5325792
【試用】Google Pixel Buds還是翻譯神器  但...
https://www.mobile01.com/topicdetail.php?f=565&t=5326102&p=2
規格與價格的絕妙平衡 Moto G5s Plus 體驗報告
https://www.mobile01.com/topicdetail.php?f=567&t=5325524
【試用】全螢幕平民機款《SUGAR C11》！2000萬雙鏡...
https://www.mobile01.com/topicdetail.php?f=586&t=5303245&p=8
【限額活動】搭載全球首款AI晶片HUAWEI Mate10/Mate10...
https://www.mobile01.com/topicdetail.php?f=629&t=5309773&p=2


In [4]:
import urllib.request

def start_requests():
    urls = [
        'https://www.mobile01.com/forumtopic.php?c=16&p=1',
        'https://www.mobile01.com/forumtopic.php?c=16&p=2',
    ]
    for url in urls:
        parseMobile01(url)

def parseMobile01(uri):
    handle = urllib.request.urlopen(uri)
    encoding = handle.headers.get_content_charset()
    html_data =  handle.read().decode(encoding)
    title = ''
    link = ''
    for a in html_data.split('class="subject"')[1:]:
        if 'topic_top' in a:
            for b in a.split('class="topic_top" title="'):
                title = b.split('">')[1].split('</a>')[0]
                link = 'https://www.mobile01.com/'+b.split('href="')[1].split('">')[0]
        elif 'topic_gen' in a:
            for b in a.split('class="topic_gen" title="'):
                title = b.split('">')[1].split('</a>')[0]
                link = 'https://www.mobile01.com/'+b.split('href="')[1].split('">')[0]
        
        print(title)
        print(link)

if __name__ == '__main__':
    start_requests();
    print("Done")





亞太魔速方塊超展開，訊號、通話更順暢！北中南體驗會開跑
https://www.mobile01.com/topicdetail.php?f=18&t=5302442&p=5
【發表會直擊】美圖V6前後雙鏡頭加持 景深美照輕鬆get
https://www.mobile01.com/topicdetail.php?f=586&t=5325792
【試用】Google Pixel Buds還是翻譯神器  但...
https://www.mobile01.com/topicdetail.php?f=565&t=5326102&p=2
規格與價格的絕妙平衡 Moto G5s Plus 體驗報告
https://www.mobile01.com/topicdetail.php?f=567&t=5325524
【試用】全螢幕平民機款《SUGAR C11》！2000萬雙鏡...
https://www.mobile01.com/topicdetail.php?f=586&t=5303245&p=8
【限額活動】搭載全球首款AI晶片HUAWEI Mate10/Mate10...
https://www.mobile01.com/topicdetail.php?f=629&t=5309773&p=2
台灣之星的vowifi 服務什麼時候有譜？
https://www.mobile01.com/topicdetail.php?f=18&t=5323817&p=2
請問htc m8維修螢幕破裂(推薦)
https://www.mobile01.com/topicdetail.php?f=566&t=5328822
台灣Mate 10簡易開箱
https://www.mobile01.com/topicdetail.php?f=629&t=5328483
[分享]台灣之星更換物流公司之後的快遞速度感想
https://www.mobile01.com/topicdetail.php?f=18&t=5328841
2018年雙11電信三雄該如何反將台灣之星一軍呢
https://www.mobile01.com/topicdetail.php?f=18&t=5326534&p=2
3G/4G分享器蓋大樓
https://www.mobile01.com/topicdetail.p

In [2]:
import urllib.request
import json

def start_requests():
    urls = [
        'https://www.mobile01.com/forumtopic.php?c=16&p=1',
    ]
    for url in urls:
        parseMobile01(url)

def parseMobile01(uri):
    handle = urllib.request.urlopen(uri)
    encoding = handle.headers.get_content_charset()
    html_data =  handle.read().decode(encoding)
    title = ''
    link = ''
    items = []
    if len(html_data.split('class="subject"'))>1:
        for a in html_data.split('class="subject"')[1:]:
            if 'topic_top' in a:
                for b in a.split('class="topic_top" title="'):
                    title = b.split('">')[1].split('</a>')[0]
                    link = 'https://www.mobile01.com/'+b.split('href="')[1].split('">')[0]
            elif 'topic_gen' in a:
                for b in a.split('class="topic_gen" title="'):
                    title = b.split('">')[1].split('</a>')[0]
                    link = 'https://www.mobile01.com/'+b.split('href="')[1].split('">')[0]
            if (len(title)>0) and (len(link)>0):
                #print(title+'\n'+link)
                items.append([title, link])
        row_json = json.dumps(items, ensure_ascii=False)
        print(row_json)
    if __name__ == '__main__':
        start_requests();
        print("Done")



In [4]:
import urllib.request
import json
import codecs

def start_requests():
    urls = [
        'https://www.mobile01.com/forumtopic.php?c=16&p=1',
    ]
    for url in urls:
        parseMobile01(url)

def parseMobile01(uri):
    handle = urllib.request.urlopen(uri)
    encoding = handle.headers.get_content_charset()
    html_data =  handle.read().decode(encoding)
    title = ''
    link = ''
    items = []
    if len(html_data.split('class="subject"'))>1:
        for a in html_data.split('class="subject"')[1:]:
            if 'topic_top' in a:
                for b in a.split('class="topic_top" title="'):
                    title = b.split('">')[1].split('</a>')[0]
                    link = 'https://www.mobile01.com/'+b.split('href="')[1].split('">')[0]
            elif 'topic_gen' in a:
                for b in a.split('class="topic_gen" title="'):
                    title = b.split('">')[1].split('</a>')[0]
                    link = 'https://www.mobile01.com/'+b.split('href="')[1].split('">')[0]
            if (len(title)>0) and (len(link)>0):
                #print(title+'\n'+link)
                items.append([title, link])
        row_json = json.dumps(dict(items), ensure_ascii=False)
        file = codecs.open('out.json', 'w', encoding='utf-8')
        file.write(row_json)
        file.close()

if __name__ == '__main__':
    start_requests();
print("Done")

Done


In [21]:
import urllib.request
import json
import codecs
import sys
import argparse as ap
import time

# def argParse():
#     parser=ap.ArgumentParser(description='Mobile01 Crawler')
#     parser.add_argument("cid", help="Mobile01 Category ID")
#     parser.add_argument("pages", help="Pages")
#     return parser.parse_args()

# args=argParse()
# cid = args.cid
# pages = args.pages


cid = '16'
pages = '1'

def start_requests():
    urls = []
    for i in range(1,int(pages)+1):
        str_idx = ''+('%s' % i)
        urls.append('https://www.mobile01.com/forumtopic.php?c='+cid+'&p='+str_idx+'')

    for url in urls:
        print (url)
        parseMobile01(url)
        time.sleep(0.5)

def parseMobile01(uri):
    handle = urllib.request.urlopen(uri)
    encoding = handle.headers.get_content_charset()
    html_data =  handle.read().decode(encoding)
    title = ''
    link = ''
    if len(html_data.split('class="subject"'))>1:
        for a in html_data.split('class="subject"')[1:]:
            if 'topic_top' in a:
                for b in a.split('class="topic_top" title="'):
                    title = b.split('">')[1].split('</a>')[0]
                    link = 'https://www.mobile01.com/'+b.split('href="')[1].split('">')[0]
            elif 'topic_gen' in a:
                for b in a.split('class="topic_gen" title="'):
                    title = b.split('">')[1].split('</a>')[0]
                    link = 'https://www.mobile01.com/'+b.split('href="')[1].split('">')[0]
            if (len(title)>0) and (len(link)>0):
                #print(title+'\n'+link)
                items.append([title, link])

if __name__ == '__main__':
    items = []
    start_requests();
    row_json = json.dumps(dict(items), ensure_ascii=False)
    file = codecs.open('16.json', 'w', encoding='utf-8')
    file.write(row_json)
    file.close()
print("Done")

https://www.mobile01.com/forumtopic.php?c=16&p=1
Done
